#!/usr/bin/bash


# === 1. Environment PRIMA DI TUTTO ===
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# === WOB (On-Screen Display) ===
rm -f $XDG_RUNTIME_DIR/wob.wob
mkfifo $XDG_RUNTIME_DIR/wob.wob
tail -f $XDG_RUNTIME_DIR/wob.wob | wob &

# === Brightness Monitor (per wob) ===
~/.local/bin/brightness-monitor.sh &

# === Blue light filter ===
#gammastep 2>/dev/null &

# === Notifications ===
mako &

# === Foot daemon ===
foot --server &

# === Wallpaper ===
swaybg -i $HOME/Pictures/mary.png -m fill &

# === Keyboard backlight ===
/usr/local/bin/kbd-backlight.sh &

# === Waybar (con delay) ===
#sleep 10
sh $HOME/scripts/waybar.sh &

# === Polkit ===
/usr/lib/polkit-kde-authentication-agent-1 &



# === GTK Settings ===
gsettings set org.gnome.desktop.interface gtk-theme Adwaita &
gsettings set org.gnome.desktop.interface cursor-theme Adwaita &
gsettings set org.gnome.desktop.interface font-name 'Jetbrains Mono 11' &
gsettings set org.gnome.desktop.interface text-scaling-factor 1 &
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' &
gsettings set org.cinnamon.desktop.default-applications.terminal exec footclient &
